// ============================================================
// Voyage — Mock Data for Development
// ============================================================

import type { Deal, Destination, Post } from "@/types";

export const mockDestinations: Destination[] = [
  {
    id: "1",
    name: "دبي",
    slug: "dubai",
    country: "الإمارات",
    countryCode: "AE",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    postsCount: 1240,
    activeDealsCount: 38,
    averageRating: 4.7,
  },
  {
    id: "2",
    name: "إسطنبول",
    slug: "istanbul",
    country: "تركيا",
    countryCode: "TR",
    imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
    postsCount: 980,
    activeDealsCount: 25,
    averageRating: 4.6,
  },
  {
    id: "3",
    name: "برشلونة",
    slug: "barcelona",
    country: "إسبانيا",
    countryCode: "ES",
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
    postsCount: 760,
    activeDealsCount: 19,
    averageRating: 4.8,
  },
  {
    id: "4",
    name: "بانكوك",
    slug: "bangkok",
    country: "تايلاند",
    countryCode: "TH",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
    postsCount: 650,
    activeDealsCount: 42,
    averageRating: 4.5,
  },
  {
    id: "5",
    name: "مراكش",
    slug: "marrakech",
    country: "المغرب",
    countryCode: "MA",
    imageUrl: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80",
    postsCount: 430,
    activeDealsCount: 15,
    averageRating: 4.6,
  },
  {
    id: "6",
    name: "روما",
    slug: "rome",
    country: "إيطاليا",
    countryCode: "IT",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
    postsCount: 890,
    activeDealsCount: 22,
    averageRating: 4.9,
  },
];

export const mockDeals: Deal[] = [
  {
    id: "1",
    title: "فندق 5 نجوم في دبي - عرض خاص للصيف",
    description: "استمتع بإقامة فاخرة في قلب دبي مع إفطار مجاني",
    category: "hotel",
    destination: mockDestinations[0],
    originalPrice: 1200,
    discountedPrice: 599,
    currency: "SAR",
    discountPercent: 50,
    sourceUrl: "#",
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    author: {
      id: "u1",
      username: "ahmed_travels",
      displayName: "أحمد المسافر",
      avatarUrl: "https://i.pravatar.cc/150?img=1",
    },
    clicksCount: 342,
    savesCount: 89,
    isExpired: false,
    isExpiringSoon: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "تذاكر طيران إسطنبول ذهاباً وإياباً",
    description: "أرخص تذاكر طيران لإسطنبول مع وجبات مجانية",
    category: "flight",
    destination: mockDestinations[1],
    originalPrice: 850,
    discountedPrice: 380,
    currency: "SAR",
    discountPercent: 55,
    sourceUrl: "#",
    expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    author: {
      id: "u2",
      username: "sara_explorer",
      displayName: "سارة المستكشفة",
      avatarUrl: "https://i.pravatar.cc/150?img=5",
    },
    clicksCount: 512,
    savesCount: 178,
    isExpired: false,
    isExpiringSoon: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "باقة برشلونة 5 ليالي شاملة",
    description: "الفندق + الطيران + جولات سياحية",
    category: "package",
    destination: mockDestinations[2],
    originalPrice: 3200,
    discountedPrice: 1890,
    currency: "SAR",
    discountPercent: 41,
    sourceUrl: "#",
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    author: {
      id: "u3",
      username: "travel_mama",
      displayName: "أم المسافرين",
      avatarUrl: "https://i.pravatar.cc/150?img=9",
    },
    clicksCount: 289,
    savesCount: 95,
    isExpired: false,
    isExpiringSoon: false,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "فندق بانكوك بوتيك 4 نجوم",
    description: "في قلب مدينة بانكوك قرب المعالم السياحية",
    category: "hotel",
    destination: mockDestinations[3],
    originalPrice: 600,
    discountedPrice: 220,
    currency: "USD",
    discountPercent: 63,
    sourceUrl: "#",
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    author: {
      id: "u4",
      username: "nomad_khalid",
      displayName: "خالد النماد",
      avatarUrl: "https://i.pravatar.cc/150?img=12",
    },
    clicksCount: 198,
    savesCount: 67,
    isExpired: false,
    isExpiringSoon: false,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockPosts: Post[] = [
  {
    id: "1",
    title: "أفضل 10 مطاعم في إسطنبول لا يجب تفويتها",
    content: "زرت إسطنبول مرتين هذا العام وجربت عشرات المطاعم...",
    category: "restaurant",
    destination: mockDestinations[1],
    images: ["https://images.unsplash.com/photo-1567897329460-9b1e9b9b9b9b?w=800&q=80"],
    tags: ["مطاعم", "إسطنبول", "تركيا"],
    author: {
      id: "u2",
      username: "sara_explorer",
      displayName: "سارة المستكشفة",
      avatarUrl: "https://i.pravatar.cc/150?img=5",
    },
    likesCount: 234,
    commentsCount: 45,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "دليل كامل للزيارة الأولى إلى مراكش",
    content: "مراكش مدينة ساحرة بألوانها وروائحها وتاريخها...",
    category: "itinerary",
    destination: mockDestinations[4],
    images: ["https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80"],
    tags: ["مراكش", "المغرب", "دليل_سياحي"],
    author: {
      id: "u1",
      username: "ahmed_travels",
      displayName: "أحمد المسافر",
      avatarUrl: "https://i.pravatar.cc/150?img=1",
    },
    likesCount: 189,
    commentsCount: 32,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
